$ cd unit_sample
$ python -m unittest
F.
======================================================================
FAIL: test_always_fail (test_unit_sample.SampleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ctrudeau/code/unit_sample/test_unit_sample.py", line 9, in test_always_fail
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
